/**
 * sRGB hex to OKLCH and back.
 *
 * A theme is generated by taking a palette that already works, reading every
 * colour in it into OKLCH, and swapping the hue. That only holds together in a
 * perceptual space: rotate a hue in HSL and the lightness moves with it -- a
 * yellow and a blue at the same HSL lightness are nowhere near as bright as
 * each other -- so the ground would go pale in one part of the circle and
 * muddy in another. In OKLCH the L stays what it says it is, which is what
 * lets the contrast the app already has survive a hue change.
 *
 * Written here rather than pulled in: it is two matrices and a cube root, the
 * app has no other use for a colour library, and the theme is loaded on every
 * page.
 */

/** Lightness 0-1, chroma 0-0.4ish, hue in degrees 0-360. */
export type Oklch = { l: number; c: number; h: number };

type Rgb = [number, number, number];

function toLinear(channel: number): number {
  return channel <= 0.04045 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4;
}

function fromLinear(channel: number): number {
  return channel <= 0.0031308 ? channel * 12.92 : 1.055 * channel ** (1 / 2.4) - 0.055;
}

/** `#rrggbb`, upper or lower case. Anything else is a caller bug, not a colour. */
export function parseHex(hex: string): Rgb {
  const match = hex.trim().match(/^#([0-9a-f]{6})$/i);
  if (!match) throw new Error(`Not a six-digit hex colour: ${hex}`);
  const pairs = match[1].match(/../g)!;
  return pairs.map((pair) => parseInt(pair, 16) / 255) as Rgb;
}

export function isHex(value: string): boolean {
  return /^#[0-9a-f]{6}$/i.test(value.trim());
}

function formatHex(rgb: Rgb): string {
  return `#${rgb
    .map((channel) => {
      const byte = Math.round(Math.min(1, Math.max(0, channel)) * 255);
      return byte.toString(16).padStart(2, '0');
    })
    .join('')}`;
}

function linearToOklab(rgb: Rgb): [number, number, number] {
  const [r, g, b] = rgb;
  const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b);
  const m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b);
  const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b);
  return [
    0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s,
    1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s,
    0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s,
  ];
}

function oklabToLinear(lab: [number, number, number]): Rgb {
  const [lightness, a, b] = lab;
  const l = (lightness + 0.3963377774 * a + 0.2158037573 * b) ** 3;
  const m = (lightness - 0.1055613458 * a - 0.0638541728 * b) ** 3;
  const s = (lightness - 0.0894841775 * a - 1.291485548 * b) ** 3;
  return [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
  ];
}

export function hexToOklch(hex: string): Oklch {
  const linear = parseHex(hex).map(toLinear) as Rgb;
  const [l, a, b] = linearToOklab(linear);
  const c = Math.hypot(a, b);
  // atan2 of two zeroes is zero, which is as good a hue as any for a grey: the
  // chroma it is multiplied by is zero too, so the number never reaches a pixel.
  const h = c === 0 ? 0 : ((Math.atan2(b, a) * 180) / Math.PI + 360) % 360;
  return { l, c, h };
}

/** Whether an OKLCH triple lands inside sRGB, with a hair of slack for float noise. */
function inGamut({ l, c, h }: Oklch): boolean {
  const radians = (h * Math.PI) / 180;
  const linear = oklabToLinear([l, c * Math.cos(radians), c * Math.sin(radians)]);
  return linear.every((channel) => channel >= -0.0001 && channel <= 1.0001);
}

/**
 * OKLCH to `#rrggbb`, giving up chroma rather than lightness when the colour
 * does not fit in sRGB.
 *
 * Rotating a hue at a fixed lightness and chroma walks off the edge of the
 * monitor in places -- sRGB holds far more saturated blue at a given lightness
 * than it does yellow. Something has to give, and it must not be the
 * lightness: the whole reason for generating in OKLCH is that every contrast
 * ratio in the app is a function of lightness, so a ground that darkened to
 * stay in gamut would take the text's readability with it. Chroma is the only
 * other thing the colour has, so chroma is what gets halved until it fits.
 */
export function oklchToHex(colour: Oklch): string {
  const h = ((colour.h % 360) + 360) % 360;
  const l = Math.min(1, Math.max(0, colour.l));
  let c = Math.max(0, colour.c);

  if (!inGamut({ l, c, h })) {
    // Sixteen halvings takes the interval below a ten-thousandth of a chroma
    // step, which is finer than an 8-bit channel can show.
    let low = 0;
    let high = c;
    for (let step = 0; step < 16; step += 1) {
      const middle = (low + high) / 2;
      if (inGamut({ l, c: middle, h })) low = middle;
      else high = middle;
    }
    c = low;
  }

  const radians = (h * Math.PI) / 180;
  const linear = oklabToLinear([l, c * Math.cos(radians), c * Math.sin(radians)]);
  return formatHex(linear.map(fromLinear) as Rgb);
}
