/**
 * sRGB hex to OKLCH and back.
 *
 * A theme is generated by taking a palette that already works, reading every
 * colour in it into OKLCH, and swapping the hue. That only holds together in a
 * perceptual space: rotate a hue in HSL and the lightness moves with it -- a
 * yellow and a blue at the same HSL lightness are nowhere near as bright as
 * each other -- so the ground would go pale in one part of the circle and
 * muddy in another. In OKLCH the L stays what it says it is, which is what
 * lets the contrast the app already has survive a hue change.
 *
 * Written here rather than pulled in: it is two matrices and a cube root, the
 * app has no other use for a colour library, and the theme is loaded on every
 * page.
 */

/** Lightness 0-1, chroma 0-0.4ish, hue in degrees 0-360. */
export type Oklch = { l: number; c: number; h: number };

type Rgb = [number, number, number];

function toLinear(channel: number): number {
  return channel <= 0.04045 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4;
}

function fromLinear(channel: number): number {
  return channel <= 0.0031308 ? channel * 12.92 : 1.055 * channel ** (1 / 2.4) - 0.055;
}

/** `#rrggbb`, upper or lower case. Anything else is a caller bug, not a colour. */
export function parseHex(hex: string): Rgb {
  const match = hex.trim().match(/^#([0-9a-f]{6})$/i);
  if (!match) throw new Error(`Not a six-digit hex colour: ${hex}`);
  const pairs = match[1].match(/../g)!;
  return pairs.map((pair) => parseInt(pair, 16) / 255) as Rgb;
}

export function isHex(value: string): boolean {
  return /^#[0-9a-f]{6}$/i.test(value.trim());
}

function formatHex(rgb: Rgb): string {
  return `#${rgb
    .map((channel) => {
      const byte = Math.round(Math.min(1, Math.max(0, channel)) * 255);
      return byte.toString(16).padStart(2, '0');
    })
    .join('')}`;
}

function linearToOklab(rgb: Rgb): [number, number, number] {
  const [r, g, b] = rgb;
  const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b);
  const m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b);
  const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b);
  return [
    0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s,
    1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s,
    0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s,
  ];
}

function oklabToLinear(lab: [number, number, number]): Rgb {
  const [lightness, a, b] = lab;
  const l = (lightness + 0.3963377774 * a + 0.2158037573 * b) ** 3;
  const m = (lightness - 0.1055613458 * a - 0.0638541728 * b) ** 3;
  const s = (lightness - 0.0894841775 * a - 1.291485548 * b) ** 3;
  return [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
  ];
}

export function hexToOklch(hex: string): Oklch {
  const linear = parseHex(hex).map(toLinear) as Rgb;
  const [l, a, b] = linearToOklab(linear);
  const c = Math.hypot(a, b);
  // atan2 of two zeroes is zero, which is as good a hue as any for a grey: the
  // chroma it is multiplied by is zero too, so the number never reaches a pixel.
  const h = c === 0 ? 0 : ((Math.atan2(b, a) * 180) / Math.PI + 360) % 360;
  return { l, c, h };
}

/** Whether an OKLCH triple lands inside sRGB, with a hair of slack for float noise. */
function inGamut({ l, c, h }: Oklch): boolean {
  const radians = (h * Math.PI) / 180;
  const linear = oklabToLinear([l, c * Math.cos(radians), c * Math.sin(radians)]);
  return linear.every((channel) => channel >= -0.0001 && channel <= 1.0001);
}

/**
 * OKLCH to `#rrggbb`, giving up chroma rather than lightness when the colour
 * does not fit in sRGB.
 *
 * Rotating a hue at a fixed lightness and chroma walks off the edge of the
 * monitor in places -- sRGB holds far more saturated blue at a given lightness
 * than it does yellow. Something has to give, and it must not be the
 * lightness: the whole reason for generating in OKLCH is that every contrast
 * ratio in the app is a function of lightness, so a ground that darkened to
 * stay in gamut would take the text's readability with it. Chroma is the only
 * other thing the colour has, so chroma is what gets halved until it fits.
 */
export function oklchToHex(colour: Oklch): string {
  const h = ((colour.h % 360) + 360) % 360;
  const l = Math.min(1, Math.max(0, colour.l));
  let c = Math.max(0, colour.c);

  if (!inGamut({ l, c, h })) {
    // Sixteen halvings takes the interval below a ten-thousandth of a chroma
    // step, which is finer than an 8-bit channel can show.
    let low = 0;
    let high = c;
    for (let step = 0; step < 16; step += 1) {
      const middle = (low + high) / 2;
      if (inGamut({ l, c: middle, h })) low = middle;
      else high = middle;
    }
    c = low;
  }

  const radians = (h * Math.PI) / 180;
  const linear = oklabToLinear([l, c * Math.cos(radians), c * Math.sin(radians)]);
  return formatHex(linear.map(fromLinear) as Rgb);
}

/**
 * The most chroma sRGB holds at one lightness and hue.
 *
 * The same bisection `oklchToHex` runs when a colour does not fit, pulled out
 * so a caller can ask the question before choosing a colour rather than after.
 * What it is for is the wash: the pools are decorative, so where a token that
 * carries text holds its chroma and gives up whatever the gamut refuses, a
 * pool wants to sit *on* that edge, and it can only do that if it can find it.
 */
export function gamutChroma(l: number, h: number): number {
  let low = 0;
  let high = 0.5;
  // Twelve halvings land within a ten-thousandth of a chroma step, and the
  // smallest difference an 8-bit channel can show is about twenty times that.
  for (let step = 0; step < 12; step += 1) {
    const middle = (low + high) / 2;
    if (inGamut({ l, c: middle, h })) low = middle;
    else high = middle;
  }
  return low;
}

/**
 * The lightness at which a hue is most colourful in sRGB, and how colourful
 * that is.
 *
 * Every hue has one, and they are nowhere near each other: blue peaks around
 * L 0.45 and yellow around L 0.93. That single fact is why rotating a hue at a
 * fixed lightness turns a good blue into a bad yellow -- a yellow held at
 * blue's lightness is brown, because brown is what a dark yellow is. Anything
 * that wants a rotated hue to look as good as the one it replaced has to know
 * where the new hue actually lives.
 *
 * A ternary search, because chroma against lightness at a fixed hue rises to
 * one peak and falls away; forty rounds take the interval below a thousandth
 * of a lightness step.
 */
export function cuspOf(h: number): { l: number; c: number } {
  const key = Math.round(((h % 360) + 360) % 360);
  const known = CUSPS.get(key);
  if (known) return known;

  let low = 0;
  let high = 1;
  for (let step = 0; step < 24; step += 1) {
    const third = (high - low) / 3;
    if (gamutChroma(low + third, key) < gamutChroma(high - third, key)) low += third;
    else high -= third;
  }
  const l = (low + high) / 2;
  const cusp = { l, c: gamutChroma(l, key) };
  CUSPS.set(key, cusp);
  return cusp;
}

/**
 * Cusps already worked out, by whole degree.
 *
 * Two hundred-odd square roots each, and the palette is generated on every
 * render and again under the cursor as the colour wheel is dragged, so they
 * are worth keeping. A whole degree is finer than the answer needs: the cusp
 * lightness moves by under a hundredth across a degree anywhere on the circle,
 * which no pixel of a wash five layers deep could show. Bounded at 360 by
 * construction.
 */
const CUSPS = new Map<number, { l: number; c: number }>();

/**
 * How far apart two colours look, as a straight line through OKLab.
 *
 * The question this answers is whether a person would take one colour for the
 * other -- which a hue angle cannot say, because two hues twenty degrees apart
 * are the same colour at one lightness and plainly different at another. OKLab
 * is near enough uniform that the distance means the same thing everywhere on
 * it, so one number serves as a floor across the whole circle. The app's four
 * written themes keep their accent between 0.16 and 0.31 from the red that
 * means delete.
 */
export function oklabDistance(a: string, b: string): number {
  const [l1, a1, b1] = linearToOklab(parseHex(a).map(toLinear) as Rgb);
  const [l2, a2, b2] = linearToOklab(parseHex(b).map(toLinear) as Rgb);
  return Math.hypot(l1 - l2, a1 - a2, b1 - b2);
}

/**
 * WCAG relative luminance, 0 for black and 1 for white.
 *
 * The quantity every contrast ratio in the app is actually a function of. It
 * is not OKLCH lightness: L is perceptual and even-handed across the circle,
 * and relative luminance weights green six times as heavily as blue. Two
 * colours at the same L, one blue and one green, differ by enough luminance to
 * move a 4.5:1 pair either side of the line.
 */
export function relativeLuminance(hex: string): number {
  const [r, g, b] = parseHex(hex).map(toLinear) as Rgb;
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

/**
 * The same hue and chroma, moved in lightness until it reflects as much light
 * as the colour it is replacing.
 *
 * This is what makes "keep the contrast it has now" true rather than
 * approximately true. Holding OKLCH lightness holds how light a colour *looks*
 * and lets the measured ratio drift -- which is how a green link on a light
 * theme came out at 4.34:1 where the blue it replaced was 4.6:1. Holding the
 * luminance instead means every pair in the palette measures exactly what the
 * reference pair measured, because both sides of every pair were matched.
 *
 * The perceptual lightness moves a little in exchange, and only for colours
 * with real chroma in them: a near-grey ground barely shifts, since there is
 * hardly any colour there for the hue to weight.
 */
export function withLuminance(colour: Oklch, target: number): string {
  // Luminance rises with lightness at a fixed hue and chroma, including where
  // gamut clamping pulls the chroma in, so a bisection finds the one answer.
  let low = 0;
  let high = 1;
  let hex = oklchToHex(colour);

  for (let step = 0; step < 24; step += 1) {
    const middle = (low + high) / 2;
    hex = oklchToHex({ ...colour, l: middle });
    if (relativeLuminance(hex) < target) low = middle;
    else high = middle;
  }

  return hex;
}
