'use client';

import { useActionState, useEffect, useState } from 'react';
import { useFormStatus } from 'react-dom';
import { Search, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Field, Input, Textarea } from '@/components/ui/field';
import { cardVariants } from '@/components/ui/card';
import { cn } from '@/lib/cn';
import { MIN_QUERY, type SearchHit } from '@/lib/search/sources';
import { MAX_QUIZ_NOTES } from '@/lib/learn/quiz/model';
import { startQuiz, type NewQuizState } from './actions';

/**
 * Choosing what to be quizzed on.
 *
 * Notes are found by typing, the same search the command palette runs, and the
 * endpoint narrows it to notes -- so this box cannot offer you an order or a
 * job application to be quizzed on. The debounce, the aborted request and the
 * rows staying put while a newer answer lands are all solved next door in
 * components/todo/link-picker.tsx and solved the same way here.
 *
 * Nothing is generated by this form. It ends with a quiz that has material and
 * no questions, and the questions are written on the screen it lands on.
 */

/** A note that has been picked, in the terms the form submits. */
type PickedNote = { id: string; title: string; subtitle: string | null };

function StartButton({ ready }: { ready: boolean }) {
  const { pending } = useFormStatus();
  return (
    <Button type="submit" disabled={pending || !ready}>
      {pending ? 'Setting it up…' : 'Start the quiz'}
    </Button>
  );
}

function NoteSearch({
  picked,
  onPick,
}: {
  picked: readonly PickedNote[];
  onPick: (note: PickedNote) => void;
}) {
  const [query, setQuery] = useState('');
  /**
   * The last answer and the query it answered, kept together so "is something
   * still on its way" is derived rather than stored. It is also what stops a
   * slow answer to an earlier query replacing a newer one.
   */
  const [answer, setAnswer] = useState<{ query: string; hits: SearchHit[] } | null>(null);

  const needle = query.trim();
  const searching = needle.length >= MIN_QUERY;
  const looking = searching && answer?.query !== needle;
  const full = picked.length >= MAX_QUIZ_NOTES;

  useEffect(() => {
    if (!searching) return;

    const controller = new AbortController();
    const timer = setTimeout(() => {
      fetch(`/api/search?q=${encodeURIComponent(needle)}&for=quiz`, { signal: controller.signal })
        .then((response) => (response.ok ? response.json() : { hits: [] }))
        .then((body: { hits?: SearchHit[] }) => setAnswer({ query: needle, hits: body.hits ?? [] }))
        .catch(() => {
          // An aborted request is the normal case rather than a failure -- the
          // next keystroke cancelled it -- and a vault that is down is not this
          // control's news to break. Either way the field still works.
        });
    }, 150);

    return () => {
      clearTimeout(timer);
      controller.abort();
    };
  }, [needle, searching]);

  const hits = (searching ? (answer?.hits ?? []) : []).filter(
    (hit) => !picked.some((note) => note.id === hit.id),
  );

  return (
    <div>
      <div className="flex items-center gap-2 border-b border-border">
        <Search className="size-4 shrink-0 text-ink-muted" strokeWidth={1.75} aria-hidden />
        <input
          value={query}
          onChange={(event) => setQuery(event.target.value)}
          onKeyDown={(event) => {
            // Never a submit: Enter in a search box means "that one", and the
            // form around it is not finished being filled in.
            if (event.key === 'Enter') event.preventDefault();
          }}
          placeholder="Find a note by name"
          aria-label="Find a note by name"
          disabled={full}
          data-focus-ring="none"
          className="h-(--control-h) w-full bg-transparent text-ui text-ink outline-none placeholder:text-ink-ghost"
        />
      </div>

      {full ? (
        <p className="px-1 py-2 text-small text-ink-muted">
          {MAX_QUIZ_NOTES} notes is as much material as one quiz is written from.
        </p>
      ) : hits.length === 0 ? (
        <p className="px-1 py-2 text-small text-ink-muted">
          {!searching
            ? 'Type a few letters of a note name or its folder.'
            : looking
              ? 'Looking…'
              : `No note matches “${needle}”.`}
        </p>
      ) : (
        <ul className="max-h-56 divide-y divide-border overflow-y-auto">
          {hits.map((hit) => (
            <li key={hit.id}>
              <button
                type="button"
                onClick={() => onPick({ id: hit.id, title: hit.title, subtitle: hit.subtitle })}
                className="press flex w-full items-center gap-2.5 rounded-control px-1 py-1.5 text-left transition-colors hover:bg-sunken"
              >
                <span className="min-w-0 flex-1 truncate text-ui text-ink">{hit.title}</span>
                {hit.subtitle && (
                  <span className="shrink-0 text-small text-ink-muted">{hit.subtitle}</span>
                )}
              </button>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

export function QuizForm({ maxPasteChars }: { maxPasteChars: number }) {
  const [state, formAction] = useActionState<NewQuizState, FormData>(startQuiz, {});
  const [picked, setPicked] = useState<PickedNote[]>([]);
  const [paste, setPaste] = useState('');

  const ready = picked.length > 0 || paste.trim().length > 0;

  return (
    <form action={formAction} className={cn(cardVariants({ padding: 'standard' }))}>
      {/* The answer travels with the form rather than through a second piece
          of state at the caller: what was picked is submitted with the rest or
          not at all. */}
      {picked.map((note) => (
        <input key={note.id} type="hidden" name="noteId" value={note.id} />
      ))}

      <Field
        label="Which notes?"
        id="quiz-notes"
        hint="Search your vault. The questions are written from what the notes say, so two or three related ones work better than everything you have."
      >
        <div id="quiz-notes">
          {picked.length > 0 && (
            <ul className="mb-2 flex flex-wrap gap-1.5">
              {picked.map((note) => (
                <li
                  key={note.id}
                  className="inline-flex max-w-xs items-center gap-1.5 rounded-pill bg-sunken py-1 pl-2.5 pr-1 text-small text-ink"
                >
                  <span className="min-w-0 truncate">{note.title}</span>
                  <button
                    type="button"
                    onClick={() => setPicked((all) => all.filter((one) => one.id !== note.id))}
                    title={`Not ${note.title}`}
                    className="press flex size-5 shrink-0 items-center justify-center rounded-full text-ink-muted transition-colors duration-150 hover:bg-accent-tint hover:text-accent"
                  >
                    <X className="size-3.5" strokeWidth={1.75} aria-hidden />
                    <span className="sr-only">Take {note.title} out of this quiz</span>
                  </button>
                </li>
              ))}
            </ul>
          )}

          <NoteSearch
            picked={picked}
            onPick={(note) => setPicked((all) => (all.some((one) => one.id === note.id) ? all : [...all, note]))}
          />
        </div>
      </Field>

      <Field
        label="Anything else to be quizzed on?"
        id="quiz-paste"
        hint="Optional. Paste anything that is not in your vault — a job description, a spec, a chapter somebody sent you."
        className="mt-4"
      >
        {/* ui-ok: composer-always-open -- the create. Choosing the material is
          * the only thing this form does, and there is nothing to read before
          * any of it has been chosen. */}
        <Textarea
          id="quiz-paste"
          name="paste"
          rows={5}
          maxLength={maxPasteChars}
          value={paste}
          onChange={(event) => setPaste(event.target.value)}
          placeholder="Paste the text here."
        />
      </Field>

      <Field
        label="What are you preparing for?"
        id="quiz-preparing-for"
        hint="Optional, and worth writing: it is what the questions get aimed at, and it is what tells two quizzes over the same notes apart."
        className="mt-4"
      >
        <Input
          id="quiz-preparing-for"
          name="preparingFor"
          maxLength={200}
          placeholder="An interview on Thursday"
        />
      </Field>

      <div className="mt-4 flex flex-wrap items-center gap-3">
        <StartButton ready={ready} />
        {state.error && <span className="text-ui text-danger">{state.error}</span>}
        {!ready && (
          <span className="text-ui text-ink-muted">Pick a note or paste something first.</span>
        )}
      </div>
    </form>
  );
}
