import type { ModuleSources } from '@/lib/sources/types';

/**
 * Learn's tables, as Goals reads them (lib/sources/types.ts). What someone
 * set out to learn is intent; what they read and were tested on is a record.
 * A new table in learn goes in one of these two lists, or the gate says so.
 */
export const learnSources: ModuleSources = {
  sources: [
    {
      table: 'learn.aims',
      module: 'Learn',
      holds: 'What they want to learn and why, each a named aim.',
      weight: 'intent',
      search: ['name', 'about'],
      title: 'name',
      href: () => '/learn/goals',
      note: 'An aim can be linked under a goal (goals.links kind aim), which shows its progress on the goal page.',
    },
    {
      table: 'learn.subjects',
      module: 'Learn',
      holds: 'The subjects they are studying, with their note on each.',
      weight: 'intent',
      search: ['name', 'note'],
      title: 'name',
      href: (id) => `/learn/s/${id}`,
    },
    {
      table: 'learn.goals',
      module: 'Learn',
      holds: 'Topics they typed in to learn, in their own words.',
      weight: 'intent',
      search: ['asked'],
      title: 'asked',
    },
    {
      table: 'learn.tracks',
      module: 'Learn',
      holds: 'Reading tracks, each answering one question.',
      weight: 'record',
      search: ['title', 'question'],
      title: 'title',
      href: (id) => `/learn/t/${id}`,
    },
    {
      table: 'learn.readings',
      module: 'Learn',
      holds: 'Things they read or mean to read, with why and their note.',
      weight: 'record',
      search: ['title', 'why', 'note'],
      title: 'title',
      href: (id) => `/learn/r/${id}`,
    },
    {
      table: 'learn.sources',
      module: 'Learn',
      holds: 'Books, articles and courses in their library.',
      weight: 'record',
      search: ['title', 'author'],
      title: 'title',
    },
    {
      table: 'learn.concepts',
      module: 'Learn',
      holds: 'Ideas they have met, with what they claim about each and how well they know it.',
      weight: 'record',
      search: ['name', 'claim'],
      title: 'name',
      href: (id) => `/learn/c/${id}`,
    },
    {
      table: 'learn.curriculum_units',
      module: 'Learn',
      holds: 'Units of a curriculum, each with what it covers and the outcome.',
      weight: 'record',
      search: ['title', 'covers', 'outcome'],
      title: 'title',
    },
    {
      table: 'learn.quizzes',
      module: 'Learn',
      holds: 'Quizzes they set themselves, and what each was preparing for.',
      weight: 'record',
      search: ['title', 'preparing_for'],
      title: 'title',
      href: (id) => `/learn/quiz/${id}`,
    },
    {
      table: 'learn.imports',
      module: 'Learn',
      holds: 'Lists they pasted in to learn from, as pasted.',
      weight: 'record',
      search: ['raw_text', 'source_hint'],
      title: 'source_hint',
    },
    {
      table: 'learn.card_notes',
      module: 'Learn',
      holds: 'Notes they wrote on Learn cards and on ideas, in their own words.',
      weight: 'intent',
      search: ['body'],
      title: 'body',
      note: 'concept_id is the idea a note is about, whose page is /learn/c/<concept_id>; card_id is the Learn now card it was written on, null when written on the idea page or once the card is gone.',
    },
    {
      table: 'learn.feed_cards',
      module: 'Learn',
      holds: 'Cards the daily feed drew for them, with whether they read, saved or passed each.',
      weight: 'incidental',
      search: ['summary', 'takeaway', 'why', 'theme_name', 'aim_name'],
      title: 'summary',
      note: 'status says what they did with a card; saved and tested cards say more than drawn ones.',
    },
  ],
  notSources: [
    { table: 'learn.area_check_articles', reason: 'Reference data for placing subjects.' },
    { table: 'learn.area_domains', reason: 'Reference data for placing subjects.' },
    { table: 'learn.area_fields', reason: 'Reference data for placing subjects.' },
    { table: 'learn.catalogue_course_items', reason: 'The shared course catalogue, not theirs.' },
    { table: 'learn.catalogue_items', reason: 'The shared course catalogue, not theirs.' },
    { table: 'learn.catalogue_judgements', reason: 'Model judgements on catalogue items.' },
    { table: 'learn.catalogue_links', reason: 'Model links from catalogue items to concepts.' },
    { table: 'learn.catalogue_providers', reason: 'The shared course catalogue, not theirs.' },
    { table: 'learn.catalogue_segments', reason: 'The shared course catalogue, not theirs.' },
    { table: 'learn.concept_edges', reason: 'Graph structure; read through concepts.' },
    { table: 'learn.concept_mentions', reason: 'Graph structure; read through concepts.' },
    { table: 'learn.concept_state', reason: 'Per-concept mastery; read through concepts.' },
    { table: 'learn.concept_subjects', reason: 'Join rows; read through subjects.' },
    { table: 'learn.next_outcomes', reason: 'Scheduling state for the feed.' },
    { table: 'learn.opening_questions', reason: 'Placement questions for a new subject.' },
    { table: 'learn.opening_sweeps', reason: 'Placement bookkeeping.' },
    { table: 'learn.probes', reason: 'Mastery-check questions and grades.' },
    { table: 'learn.quiz_questions', reason: 'Questions inside a quiz; read through quizzes.' },
    { table: 'learn.quiz_sources', reason: 'Material a quiz was written from.' },
    { table: 'learn.theme_fields', reason: 'Model placement of vault themes.' },
    { table: 'learn.track_offers', reason: 'Tracks the feed offered.' },
    { table: 'learn.transcript_calls', reason: 'Transcript fetch bookkeeping.' },
    { table: 'learn.video_transcripts', reason: 'Transcript storage.' },
  ],
};
