import type { ModuleSources } from '@/lib/sources/types';

/**
 * The job search's tables, as Goals reads them (lib/sources/types.ts). A new
 * table in job_search goes in one of these two lists, or the gate says so.
 */
export const jobsSources: ModuleSources = {
  sources: [
    {
      table: 'job_search.thoughts',
      module: 'Job search',
      holds: 'What the person is looking for in the next job and where they are now, in their own words, one dated entry at a time.',
      weight: 'intent',
      search: ['body'],
      title: 'body',
      href: () => '/jobs/thoughts',
      note: 'A newer entry supersedes an older one where they disagree; read them newest first.',
    },
    {
      table: 'job_search.profiles',
      module: 'Job search',
      holds: 'The titles they are targeting and how they like their writing to sound.',
      weight: 'intent',
      search: ['target_titles', 'writing_style_notes'],
      title: 'display_name',
      owner: 'id',
      href: () => '/jobs/settings',
    },
    {
      table: 'job_search.roles',
      module: 'Job search',
      holds: 'Each role they are considering or have applied to, with its description and requirements.',
      weight: 'record',
      search: ['title', 'jd_text', 'location', 'seniority', 'requirements'],
      title: 'title',
      href: (id) => `/jobs/roles/${id}`,
    },
    {
      table: 'job_search.applications',
      module: 'Job search',
      holds: 'Each application, its stage and the next thing to do on it.',
      weight: 'record',
      search: ['next_action'],
      title: 'next_action',
      href: () => '/jobs/pipeline',
      note: 'Name one by its role (role_id → roles.title). Count them for a job-search goal rather than copying them.',
    },
    {
      table: 'job_search.application_events',
      module: 'Job search',
      holds: 'What happened on each application and when: sent, heard back, rejected, offered.',
      weight: 'record',
      search: ['summary'],
      title: 'summary',
      owner: 'user_id',
    },
    {
      table: 'job_search.interviews',
      module: 'Job search',
      holds: 'Interviews, with their prep and what was asked.',
      weight: 'record',
      search: ['notes', 'prep_notes', 'questions_asked'],
      title: 'notes',
      href: () => '/jobs/interviews',
      note: 'Name one by its application’s role (application_id → applications.role_id → roles.title).',
    },
    {
      table: 'job_search.companies',
      module: 'Job search',
      holds: 'Companies they are tracking, with industry, stage and research notes.',
      weight: 'record',
      search: ['name', 'industry', 'research', 'hq_location'],
      title: 'name',
      ref: 'slug',
      href: (slug) => `/jobs/companies/${encodeURIComponent(slug)}`,
    },
    {
      table: 'job_search.contacts',
      module: 'Job search',
      holds: 'People in their network for the search and how they know them.',
      weight: 'record',
      search: ['full_name', 'title', 'how_we_connect', 'notes'],
      title: 'full_name',
      href: (id) => `/jobs/contacts/${id}`,
    },
    {
      table: 'job_search.contact_touches',
      module: 'Job search',
      holds: 'Each time they reached out to a contact, and what came back.',
      weight: 'record',
      search: ['message', 'response_summary'],
      title: 'message',
    },
    {
      table: 'job_search.notes',
      module: 'Job search',
      holds: 'Notes they wrote on roles, companies and applications.',
      weight: 'record',
      search: ['body'],
      title: 'body',
    },
    {
      table: 'job_search.evidence_items',
      module: 'Job search',
      holds: 'Stories of their own work and results, used as evidence in applications.',
      weight: 'record',
      search: ['title', 'body', 'context', 'skills'],
      title: 'title',
      href: () => '/jobs/answers',
    },
    {
      table: 'job_search.resume_versions',
      module: 'Job search',
      holds: 'Each version of their résumé, as text.',
      weight: 'record',
      search: ['label', 'text_content', 'notes'],
      title: 'label',
    },
    {
      table: 'job_search.cover_letters',
      module: 'Job search',
      holds: 'Cover letters they sent.',
      weight: 'record',
      search: ['body'],
      title: 'body',
    },
    {
      table: 'job_search.application_answers',
      module: 'Job search',
      holds: 'Their answers to application questions.',
      weight: 'record',
      search: ['answer'],
      title: 'answer',
    },
    {
      table: 'job_search.questions',
      module: 'Job search',
      holds: 'Application questions they have met, with their standing answer.',
      weight: 'record',
      search: ['text', 'canonical_answer'],
      title: 'text',
    },
    {
      table: 'job_search.reminders',
      module: 'Job search',
      holds: 'Follow-ups the job search is reminding them of.',
      weight: 'record',
      search: ['body'],
      title: 'body',
      href: () => '/jobs/today',
    },
  ],
  notSources: [
    { table: 'job_search.attachments', reason: 'Uploaded files; their text is in resume_versions.' },
    { table: 'job_search.excluded_senders', reason: 'Mail filtering settings.' },
    { table: 'job_search.ingested_messages', reason: 'Mail sync bookkeeping.' },
    { table: 'job_search.interview_groups', reason: 'Groups the interviews of one loop; the interviews hold the notes.' },
    { table: 'job_search.interview_group_messages', reason: 'Join rows between groups and mail.' },
    { table: 'job_search.learning_tracks', reason: 'Tracks Claude suggested from the career goals; the ones started are Learn goals in learn.aims.' },
    { table: 'job_search.interview_participants', reason: 'Join rows between interviews and contacts.' },
    { table: 'job_search.message_link_dismissals', reason: 'Dismissed suggestions in the inbox.' },
    { table: 'job_search.quiet_dismissals', reason: 'Dismissed quiet-application nudges.' },
    { table: 'job_search.waiting_dismissals', reason: 'Dismissed waiting-on-reply nudges.' },
  ],
};
